{% set version = "1.5.43" %}

{% if 1 %}{% set cov = "coverage run --source=schedula --branch --append -m" %}{% endif %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: schedula
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/s/schedula/schedula-{{ version }}.tar.gz
    sha256: 06f7453418e8ac27e50f5e8f767efc920f6f81a8305e3b2e44bb569cebd7335e
    folder: dist
  - url: https://github.com/vinci1it2000/schedula/archive/v{{ version }}.tar.gz
    sha256: 0b682c8a2dac4abcf31f4e544eceffa8258d45f4e61088358f64a7aeda8d38d2
    folder: src

build:
  number: 0
  noarch: python
  script:
    - cd dist && {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - schedula = schedula.cli:cli

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  requires:
    - pip
  imports:
    - schedula
  commands:
    - pip check
    - which schedula || where schedula

outputs:
  - name: schedula

  - name: schedula-with-io
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("schedula", max_pin="x.x.x") }}
        - dill !=0.2.7
    test:
      requires:
        - pip
      imports:
        - schedula
      commands:
        - pip check

  - name: schedula-with-web
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("schedula", max_pin="x.x.x") }}
        - flask
        - regex
        - requests
    test:
      requires:
        - pip
      imports:
        - schedula
      commands:
        - pip check

  - name: schedula-with-parallel
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("schedula", max_pin="x.x.x") }}
        - multiprocess !=0.70.17
    test:
      files:
        - pip_check.py
      requires:
        - pip
      imports:
        - schedula
      commands:
        - python pip_check.py "multiprocess .* is not supported on this platform"

  - name: schedula-with-plot
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("schedula-with-web", max_pin="x.x.x") }}
        - {{ pin_subpackage("schedula", max_pin="x.x.x") }}
        - python-graphviz >=0.17
        - pygments
        - jinja2
        - docutils
    test:
      requires:
        - pip
      imports:
        - schedula
      commands:
        - pip check

  - name: schedula-with-form
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("schedula-with-web", max_pin="x.x.x") }}
        - {{ pin_subpackage("schedula", max_pin="x.x.x") }}
        - asteval
        - click-log
        - click
        - fasteners
        - flask-admin
        - flask-babel
        - flask-mail
        - flask-principal
        - flask-sqlalchemy
        - flask-wtf
        - gunicorn
        - itsdangerous
        - rst2txt
        - sqlalchemy
        - stripe
        # from flask-security-too[common]
        - flask-security-too
        - argon2-cffi >=21.3.0
        - bcrypt >=4.0.1
        - bleach >=6.0.0
        # TODO: build for conda-forge
        # - flask-mailman >=0.3.0
        # - sherlock
        # - sqlalchemy-file
    test:
      requires:
        - pip
      imports:
        - schedula
      commands:
        - pip check
        - schedula form --help

  - name: schedula-with-all
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage("schedula-with-form", max_pin="x.x.x") }}
        - {{ pin_subpackage("schedula-with-io", max_pin="x.x.x") }}
        - {{ pin_subpackage("schedula-with-parallel", max_pin="x.x.x") }}
        - {{ pin_subpackage("schedula-with-plot", max_pin="x.x.x") }}
        - {{ pin_subpackage("schedula-with-web", max_pin="x.x.x") }}
        - {{ pin_subpackage("schedula", max_pin="x.x.x") }}
    test:
      files:
        - pip_check.py
      source_files:
        - src/examples
        - src/tests/test_dispatcher.py
        - src/tests/test_import.py
        - src/tests/utils
        - src/setup.cfg
      requires:
        - pip
        # some weird issue
        - python <3.12
        # tests-require
        - coverage
        - cryptography
        - ddt
      imports:
        - schedula
      commands:
        - python pip_check.py "multiprocess .* is not supported on this platform"
        # doesn't import without chromedriver stuff
        - python -c "__import__('pathlib').Path('src/tests/utils/test_form.py').unlink()"
        # requires `schedula.ext.form` to be importable
        - schedula --help
        - schedula form --help
        - {{ cov }} schedula.cli --help
        - {{ cov }} schedula.cli form --help
        - {{ cov }} unittest discover --start-directory src/tests --pattern 'test_*.py'
        - coverage report --show-missing --skip-covered --fail-under=63

about:
  home: https://github.com/vinci1it2000/schedula
  license: EUPL-1.1
  license_family: OTHER
  license_file: src/LICENSE.txt
  summary: |-
    Produce a plan that dispatches calls based on a graph of functions, satisfying
    data dependencies.
  doc_url: https://schedula.readthedocs.io/en/v{{ version }}
  doc_source_url: https://github.com/vinci1it2000/schedula/tree/v{{ version }}/doc

extra:
  feedstock-name: schedula-split
  recipe-maintainers:
    - bollwyvl
