# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.6.15"
  python_check_max: "3.14"

recipe:
  name: schedula
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/s/schedula/schedula-${{ version }}.tar.gz
    sha256: 85654c82cb8e73fb5ca48952c317119157cd8da248c9d395bac90ffb9a01927c
    target_directory: dist
  - url: https://github.com/vinci1it2000/schedula/archive/v${{ version }}.tar.gz
    sha256: 5a5cf98294999bb20fff79d6f5cda8e0423a39df5fbab69e655c300d61041b2d
    target_directory: src

build:
  number: 0

outputs:
  - package:
      name: schedula
    build:
      noarch: python
      script:
        - cd dist
        - ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
      python:
        entry_points:
          - schedula = schedula.cli:cli
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
        - setuptools
      run:
        - python >=${{ python_min }}
    tests:
      - python:
          imports: schedula
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - which schedula || where schedula

  - package:
      name: schedula-with-io
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("schedula", upper_bound="x.x.x") }}
        - dill !=0.2.7
    tests:
      - python:
          imports: schedula
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*

  - package:
      name: schedula-with-web
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("schedula", upper_bound="x.x.x") }}
        - flask
        - regex
        - requests
    tests:
      - python:
          imports: schedula
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
  - package:
      name: schedula-with-parallel
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("schedula", upper_bound="x.x.x") }}
        - multiprocess !=0.70.17
    tests:
      - python:
          imports: schedula
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
  - package:
      name: schedula-with-plot
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("schedula-with-web", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("schedula", upper_bound="x.x.x") }}
        - python-graphviz >=0.17
        - pygments
        - jinja2
        - docutils
    tests:
      - python:
          imports: schedula
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
  - package:
      name: schedula-with-form
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("schedula-with-web", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("schedula", upper_bound="x.x.x") }}
        - apprise
        - asteval
        - boto3
        - click
        - click-log
        - docutils
        - flask-admin
        - flask-babel
        - flask-mail
        - flask-principal
        - flask-pymongo
        - flask-security
        - flask-sqlalchemy
        - flask-wtf
        - gunicorn
        - itsdangerous
        - jsonschema
        - pydash
        - python-dateutil
        - sqlalchemy
        - stripe
        # from flask-security[common]
        - flask-security-too
        - argon2-cffi >=21.3.0
        - bcrypt >=4.0.1
        - bleach >=6.0.0
        # TODO: build for conda-forge
        # - casbin
        # - flask-mailman >=0.3.0
        # - mongo-schema
        # - sherlock
        # - sqlalchemy-adapter
        # - sqlalchemy-file
    tests:
      - python:
          imports:
            - schedula
            - schedula.utils.form.server.items
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - schedula form --help
  - package:
      name: schedula-with-all
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("schedula-with-form", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("schedula-with-io", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("schedula-with-parallel", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("schedula-with-plot", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("schedula-with-web", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("schedula", upper_bound="x.x.x") }}
    tests:
      - python:
          imports: schedula
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - ${{ python_check_max }}.*
      - files:
          recipe:
            - run_test.py
          source:
            - src/examples/
            - src/tests/test_dispatcher.py
            - src/tests/test_import.py
            - src/tests/utils/
            - src/setup.cfg
        requirements:
          run:
            - python ${{ python_min }}.*
            - coverage
            - cryptography
            - ddt
        script:
          - python run_test.py

about:
  license: EUPL-1.1
  license_file: src/LICENSE.txt
  summary: |-
    Produce a plan that dispatches calls based on a graph of functions, satisfying
    data dependencies.
  homepage: https://pypi.org/project/schedula
  repository: https://github.com/vinci1it2000/schedula
  documentation: https://schedula.readthedocs.io

extra:
  feedstock-name: schedula
  recipe-maintainers:
    - bollwyvl
